# Generated by Django 3.2.8 on 2021-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+91', max_length=11),
        ),
    ]
