# Generated by Django 3.2.8 on 2021-11-05 05:57

import auth_app.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_type', enumchoicefield.fields.EnumChoiceField(enum_class=auth_app.models.TokenType, max_length=31)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('updating_value', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
