# Generated by Django 3.2.8 on 2021-11-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
            preserve_default=False,
        ),
    ]
