# Generated by Django 3.2.8 on 2021-11-03 06:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import doctor_app.models
import enumchoicefield.fields
import hospital_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_role', enumchoicefield.fields.EnumChoiceField(enum_class=doctor_app.models.ClientStaffRoles, max_length=14)),
                ('responsibilities', django.contrib.postgres.fields.ArrayField(base_field=enumchoicefield.fields.EnumChoiceField(enum_class=doctor_app.models.ClientStaffPermissions, max_length=20), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_type', enumchoicefield.fields.EnumChoiceField(enum_class=doctor_app.models.ConsultationType, max_length=8)),
                ('location', models.TextField()),
                ('charge', models.FloatField()),
                ('remark', models.TextField()),
                ('slot_duration', models.IntegerField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_address', to='hospital_app.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=256)),
                ('institute', models.CharField(max_length=256)),
                ('passing_year', models.IntegerField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('relates_speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_app.speciality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_app.user')),
                ('dob', models.DateField()),
                ('image', models.TextField()),
                ('practice_start_year', models.IntegerField()),
                ('details', models.TextField(blank=True)),
                ('additional_details', models.TextField(blank=True)),
                ('hospitals', models.ManyToManyField(to='hospital_app.Hospital')),
                ('qualifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_app.qualification')),
                ('specialitities', models.ManyToManyField(to='doctor_app.Speciality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('slots', models.CharField(max_length=15)),
                ('availablity', enumchoicefield.fields.EnumChoiceField(enum_class=doctor_app.models.SlotAvailablity, max_length=9)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationDefalutTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_name', enumchoicefield.fields.EnumChoiceField(enum_class=hospital_app.models.Weekday, max_length=9)),
                ('start_hour', models.PositiveIntegerField()),
                ('start_minute', models.PositiveIntegerField()),
                ('start_period', enumchoicefield.fields.EnumChoiceField(enum_class=hospital_app.models.SlotPeriod, max_length=2)),
                ('end_hour', models.PositiveIntegerField()),
                ('end_minute', models.PositiveIntegerField()),
                ('end_period', enumchoicefield.fields.EnumChoiceField(enum_class=hospital_app.models.SlotPeriod, max_length=2)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_doctor', to='doctor_app.doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_hospital', to='hospital_app.hospital'),
        ),
        migrations.CreateModel(
            name='ClientStaffSecondaryRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secondary_role', enumchoicefield.fields.EnumChoiceField(enum_class=doctor_app.models.ClientStaffRoles, max_length=14)),
                ('permissons', django.contrib.postgres.fields.ArrayField(base_field=enumchoicefield.fields.EnumChoiceField(enum_class=doctor_app.models.ClientStaffPermissions, max_length=20), size=None)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cs_secondary_role_doctor', to='doctor_app.doctor')),
                ('hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cs_secondary_role_hospital', to='hospital_app.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_secondary_role_user', to='doctor_app.clientstaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientstaff',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_staff_doctor', to='doctor_app.doctor'),
        ),
        migrations.AddField(
            model_name='clientstaff',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_staff_hospital', to='hospital_app.hospital'),
        ),
        migrations.AddField(
            model_name='clientstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_staff_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
