# Generated by Django 3.2.8 on 2021-11-05 05:57

import admin_app.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import user_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
        ('auth_app', '0003_verificationtoken'),
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_app.user')),
                ('dob', models.DateField()),
                ('image', models.TextField()),
                ('post', enumchoicefield.fields.EnumChoiceField(enum_class=admin_app.models.AdminStaffPosts, max_length=37)),
                ('designation', models.CharField(blank=True, max_length=256)),
                ('department', enumchoicefield.fields.EnumChoiceField(enum_class=admin_app.models.Department, max_length=16)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=enumchoicefield.fields.EnumChoiceField(enum_class=admin_app.models.AdminStaffPermissions, max_length=29), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('other_details', models.TextField()),
                ('used_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCompositionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescribed_by_other', models.CharField(blank=True, max_length=256)),
                ('prescription', models.TextField(blank=True)),
                ('estimated_amount', models.FloatField()),
                ('final_amount', models.FloatField()),
                ('expected_delivery_date', models.DateField()),
                ('appointment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.appointment')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_app.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_form', enumchoicefield.fields.EnumChoiceField(enum_class=admin_app.models.MedicineForm, max_length=12)),
                ('quantity_per_unit', models.PositiveIntegerField()),
                ('volume_per_unit', models.PositiveIntegerField()),
                ('unit_details', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturing_date', models.PositiveIntegerField()),
                ('manufacturing_month', models.PositiveIntegerField()),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('expiry_date', models.PositiveIntegerField()),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('mrp', models.FloatField()),
                ('discount', models.PositiveIntegerField()),
                ('discount_type', enumchoicefield.fields.EnumChoiceField(enum_class=user_app.models.DiscountType, max_length=13)),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.medicine')),
                ('medicine_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.medicineunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=admin_app.models.OrderStatus(1), enum_class=admin_app.models.OrderStatus, max_length=19)),
                ('details', models.CharField(blank=True, max_length=256)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('medicine_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.medicineorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.medicineorder')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.ManyToManyField(related_name='medicine_composition', to='admin_app.MedicineCompositionElement'),
        ),
    ]
